export const supportedLocales = ['en', 'zh'];

const dictionaries = {
  en: {
    'app.aria': 'hello-world AI client',
    'skip.composer': 'Skip to composer',
    'sidebar.workspace': 'Workspace',
    'brand.localFirst': 'Local first',
    'action.newChat': 'New chat',
    'session.conversations': 'Conversations',
    'session.searchPlaceholder': 'Search chats',
    'session.scope': 'Conversation scope',
    'session.scope.active': 'Active chats',
    'session.scope.archived': 'Archived chats',
    'session.scope.deleted': 'Trash',
    'session.scope.all': 'All chats',
    'session.tag': 'Conversation tag',
    'session.allTags': 'All tags',
    'session.history': 'Chat history',
    'session.current': 'Current chat',
    'session.currentHint': 'tags, pin, archive',
    'session.tags': 'Tags',
    'session.tagPlaceholder': 'research, work',
    'session.pin': 'Pin',
    'session.archive': 'Archive',
    'session.save': 'Save chat',
    'session.moveTrash': 'Move to trash',
    'session.restore': 'Restore',
    'session.deleteForever': 'Delete forever',
    'session.status': '{active} active / {archived} archived / {total} total',
    'session.badge.pinned': 'Pinned',
    'session.badge.archived': 'Archived',
    'session.badge.trash': 'Trash',
    'session.empty.matching': 'No matching conversations.',
    'session.empty.archived': 'No archived conversations.',
    'session.empty.default': 'No conversations yet.',
    'session.messageCount.one': '{count} message',
    'session.messageCount.many': '{count} messages',
    'local.status': 'Local status',
    'local.runtimeKeysOnly': 'Runtime keys only',
    'chat.aria': 'Chat',
    'chat.privateWorkspace': 'Private AI workspace',
    'chat.untitled': 'Untitled chat',
    'model.compatible': 'Native and compatible providers',
    'usage.tokens': '{count} tokens',
    'settings.link': 'Settings',
    'branch.results': 'Message branches',
    'comparison.results': 'Model comparison results',
    'attachments.aria': 'Attachments',
    'composer.tools': 'Input tools',
    'composer.attach': 'Attach',
    'composer.screenshot': 'Screenshot',
    'composer.pasteImage': 'Paste image',
    'composer.camera': 'Camera',
    'composer.voice': 'Voice',
    'composer.speakLast': 'Speak last',
    'composer.placeholder': 'Message hello-world...',
    'composer.message': 'Message',
    'composer.send': 'Send',
    'composer.branchLast': 'Branch last',
    'composer.compare': 'Compare',
    'composer.stop': 'Stop',
    'settings.aria': 'Settings',
    'settings.eyebrow': 'Workspace settings',
    'settings.title': 'Settings',
    'settings.description': 'Manage providers, assistants, prompts, routing, local data, and safety defaults outside the chat surface.',
    'settings.back': 'Back to chat',
    'settings.sections': 'Sections',
    'settings.provider': 'Provider',
    'settings.agent': 'Agent',
    'settings.prompts': 'Prompts',
    'settings.routing': 'Routing',
    'settings.cost': 'Cost',
    'settings.sync': 'Sync',
    'settings.backup': 'Backup',
    'settings.security': 'Security',
    'settings.advanced': 'Advanced',
    'settings.coreSetup': 'Core setup',
    'settings.coreHeading': 'Connection, assistant, and prompts',
    'settings.workflow': 'Workflow',
    'settings.workflowHeading': 'Routing and cost controls',
    'settings.localData': 'Local data',
    'settings.dataHeading': 'Sync and backup',
    'settings.safety': 'Safety',
    'settings.safetyHeading': 'Default blocked capabilities',
    'settings.advancedHeading': 'RAG, search, MCP, plugins, and Desktop code',
    'provider.connection': 'Connection',
    'provider.preset': 'Preset',
    'provider.presetManual': 'Custom / manual',
    'provider.presetManualReady': 'Manual provider settings are ready.',
    'provider.presetApplied': '{name} preset loaded with {model}. Enter the runtime API key, then save.',
    'provider.modelManual': 'manual model',
    'provider.category.cloud': 'Cloud APIs',
    'provider.category.gateway': 'Gateways / relays',
    'provider.category.local': 'Local runtimes',
    'field.name': 'Name',
    'field.type': 'Type',
    'field.baseUrl': 'Base URL',
    'field.model': 'Model',
    'field.apiKey': 'API key',
    'provider.namePlaceholder': 'Local Ollama',
    'provider.modelPlaceholder': 'gpt-4.1-mini or llama3.2',
    'provider.keyPlaceholder': 'Runtime only; not persisted',
    'provider.detectOllama': 'Detect Ollama',
    'action.save': 'Save',
    'provider.noneConfigured': 'No provider configured.',
    'provider.localEcho': 'No provider configured. Local echo mode is active.',
    'provider.saved': 'Saved {name} ({model}). API keys stay in memory for this browser tab.',
    'agent.preset': 'Agent preset',
    'agent.persona': 'Persona',
    'agent.activePreset': 'Active preset',
    'agent.noPreset': 'No preset',
    'agent.icon': 'Icon',
    'agent.defaultModel': 'Default model',
    'agent.systemPrompt': 'System prompt',
    'agent.enabledTools': 'Enabled tools',
    'agent.knowledgeBase': 'Knowledge base',
    'agent.namePlaceholder': 'Research editor',
    'agent.iconPlaceholder': 'AI',
    'agent.modelPlaceholder': 'Optional model override',
    'agent.promptPlaceholder': 'How should this agent behave?',
    'agent.toolsPlaceholder': 'file-attachments, vision-input',
    'agent.knowledge.none': 'None',
    'agent.knowledge.session': 'Session',
    'agent.knowledge.library': 'Library',
    'agent.save': 'Save agent',
    'agent.noneActive': 'No preset active.',
    'agent.noneActiveDetail': 'No preset active. Provider calls use the normal chat context.',
    'agent.activeDetail': '{icon} {name} active. System prompt is prepended at runtime; tools remain governed by security defaults.',
    'agent.savedActive': '{icon} {name} is active for new provider calls.',
    'prompt.library': 'Prompt library',
    'prompt.template': 'Template',
    'prompt.activeTemplate': 'Active template',
    'prompt.noTemplate': 'No template',
    'prompt.title': 'Title',
    'prompt.body': 'Template body',
    'prompt.variables': 'Variables',
    'prompt.variablesJson': 'Variables JSON',
    'prompt.tags': 'Tags',
    'prompt.scope': 'Scope',
    'prompt.scope.local': 'Local',
    'prompt.scope.sync': 'Sync-ready',
    'prompt.favorite': 'Favorite',
    'prompt.apply': 'Apply',
    'prompt.titlePlaceholder': 'Meeting summary',
    'prompt.bodyPlaceholder': 'Summarize {{ topic }} for {{ audience }}.',
    'prompt.variablesPlaceholder': 'topic, audience',
    'prompt.valuesPlaceholder': '{"topic":"launch plan","audience":"team"}',
    'prompt.tagsPlaceholder': 'work, writing',
    'prompt.noneSelected': 'No template selected.',
    'prompt.noneSelectedDetail': 'No template selected. Save one to reuse prompts.',
    'prompt.saved': '{title} saved and ready to apply.',
    'prompt.selected': '{title} selected. Fill Variables JSON, then apply.',
    'prompt.chooseBeforeApply': 'Choose or save a template before applying.',
    'prompt.applied': '{title} applied to the composer.',
    'prompt.appliedMissing': 'Applied with unresolved variables: {variables}.',
    'prompt.variablesError': 'Template variables error: {message}',
    'prompt.variablesObjectOnly': 'Variables JSON must be an object.',
    'prompt.invalidJson': 'Invalid JSON.',
    'routing.router': 'Model router',
    'routing.route': 'Route',
    'routing.strategy': 'Strategy',
    'routing.balanced': 'Balanced',
    'routing.cheap': 'Cheap first',
    'routing.fast': 'Fast first',
    'routing.longContext': 'Long context',
    'routing.privacy': 'Privacy first',
    'routing.fallback': 'Fallback',
    'routing.noProvider': 'No enabled provider is available for routing.',
    'routing.chose': 'Routing chose {name} / {model} ({reasons}).',
    'routing.reason.lowCostMini': 'low-cost mini model',
    'routing.reason.localNoBilling': 'local model without provider billing',
    'routing.reason.standardRemotePricing': 'standard remote pricing',
    'routing.reason.smallFastModel': 'small fast model',
    'routing.reason.localLatency': 'local model latency depends on device',
    'routing.reason.standardLatency': 'standard model latency',
    'routing.reason.contextWindow': '{context} context window',
    'routing.reason.localPrivate': 'local/private provider',
    'routing.reason.remoteProvider': 'remote provider',
    'routing.reason.fallback': 'first available fallback',
    'routing.reason.balanced': 'balanced priority',
    'budget.usage': 'Usage budget',
    'budget.dailyLimit': 'Daily limit',
    'budget.monthlyLimit': 'Monthly limit',
    'budget.currency': 'Currency',
    'budget.save': 'Save budget',
    'budget.estimated': '{amount} estimated. {message}',
    'budget.noUsage': 'No usage',
    'budget.latestDay': 'Latest day',
    'budget.latestMonth': 'Latest month',
    'budget.monthlyReached': 'Monthly budget reached: {current} / {limit}.',
    'budget.dailyReached': 'Daily budget reached: {current} / {limit}.',
    'budget.ok': 'Budget OK: today {today}, month {month}.',
    'sync.foundation': 'Sync foundation',
    'sync.localSync': 'Local sync',
    'sync.status': 'Status',
    'sync.localOnly': 'Local only',
    'sync.enabled': 'Enabled',
    'sync.endpoint': 'Endpoint',
    'sync.scopes': 'Scopes',
    'sync.preview': 'Preview',
    'sync.save': 'Save sync',
    'sync.disabled': 'Local sync is disabled.',
    'sync.counts': 'Sync counts',
    'sync.settingsSaved': 'Sync settings saved locally. No network call was sent.',
    'sync.previewOnly': '{status} Preview only; conflicts will require explicit choice.',
    'sync.upload': 'Upload',
    'sync.download': 'Download',
    'sync.conflicts': 'Conflicts',
    'sync.noEndpoint': 'No sync endpoint configured',
    'sync.noScopes': 'No scopes selected',
    'sync.target.chats': 'chats',
    'sync.target.settings': 'settings',
    'sync.target.providers': 'providers',
    'sync.target.prompts': 'prompts',
    'sync.target.agents': 'agents',
    'sync.target.knowledgeMetadata': 'knowledge metadata',
    'sync.conflictNeedsReview': '{count} conflict{plural} need explicit review before sync.',
    'sync.noPendingAt': 'No pending sync changes as of {checkedAt}.',
    'sync.noPending': 'No pending sync changes.',
    'sync.readyCounts': '{upload} upload{uploadPlural} and {download} download{downloadPlural} ready.',
    'backup.importExport': 'Import / export',
    'backup.description': 'Export Markdown for one session or JSON for a full local restore.',
    'backup.payload': 'Backup payload',
    'backup.payloadPlaceholder': 'Exported Markdown or hello-world JSON backup appears here. Paste JSON here before restore.',
    'backup.markdown': 'Markdown',
    'backup.json': 'JSON backup',
    'backup.restore': 'Restore',
    'backup.ready': 'Ready to export local data.',
    'backup.readyDetail': 'Ready to export: {summary}',
    'backup.jsonReady': 'JSON backup ready: {summary} Copy it to a local file.',
    'backup.markdownReady': 'Active session Markdown export is ready with sensitive text redacted.',
    'backup.restored': 'Backup restored locally. Provider API keys must be re-entered at runtime.',
    'backup.restoreFailed': 'Restore failed: {message}',
    'backup.invalidJson': 'Invalid backup JSON.',
    'backup.summary': '{sessions} session{sessionPlural}, {prompts} prompt{promptPlural}, {agents} agent{agentPlural}, {providers} provider{providerPlural}.',
    'security.defaults': 'Security defaults',
    'security.terminal': 'Terminal',
    'security.codeExecution': 'Code execution',
    'security.stdioMcp': 'stdio MCP',
    'security.broadFilesystem': 'Broad filesystem',
    'security.off': 'off',
    'advanced.enabled': 'Enabled',
    'advanced.rag': 'RAG',
    'advanced.ragHeading': 'Knowledge retrieval',
    'advanced.sourceScope': 'Source scope',
    'advanced.scopeSession': 'Session',
    'advanced.scopeLibrary': 'Library',
    'advanced.scopeBoth': 'Session + library',
    'advanced.embeddingProvider': 'Embedding provider',
    'advanced.localEmbedding': 'Local deterministic',
    'advanced.remoteEmbedding': 'Remote runtime provider',
    'advanced.indexMode': 'Index mode',
    'advanced.lightweightIndex': 'Lightweight Web/Mobile',
    'advanced.desktopDurableIndex': 'Desktop durable',
    'advanced.retrievalMode': 'Retrieval',
    'advanced.maxChunks': 'Max chunks',
    'advanced.requireCitations': 'Require citations',
    'advanced.reranking': 'Reranking',
    'advanced.saveRag': 'Save RAG',
    'advanced.ragReady': 'RAG settings are ready.',
    'advanced.ragSummary': '{scope} retrieval uses {retrieval} mode with up to {chunks} chunks.',
    'advanced.savedRag': 'RAG settings saved locally.',
    'advanced.webSearch': 'Web search',
    'advanced.webSearchHeading': 'Grounded answers',
    'advanced.searchProvider': 'Provider',
    'advanced.custom': 'Custom',
    'advanced.maxResults': 'Max results',
    'advanced.groundedAnswers': 'Grounded answers',
    'advanced.desktopProxy': 'Desktop proxy fallback',
    'advanced.saveWebSearch': 'Save search',
    'advanced.webSearchReady': 'Search settings are ready.',
    'advanced.webSearchSummary': '{provider} configured for up to {results} result(s).',
    'advanced.savedWebSearch': 'Web search settings saved locally. Runtime search keys are not persisted.',
    'advanced.mcp': 'MCP / plugins',
    'advanced.mcpHeading': 'Tool servers',
    'advanced.httpMcp': 'HTTP MCP',
    'advanced.tools': 'Tools',
    'advanced.pluginManager': 'Desktop plugin manager',
    'advanced.stdioMcp': 'Desktop stdio MCP',
    'advanced.requireConfirmation': 'Require confirmation',
    'advanced.saveMcp': 'Save MCP',
    'advanced.mcpReady': 'MCP settings are ready.',
    'advanced.mcpSharedSummary': 'HTTP MCP is available as the shared safe subset. Desktop-only controls are disabled here.',
    'advanced.mcpDesktopSummary': 'Desktop plugin controls are visible, but confirmation and policy gates still apply.',
    'advanced.savedMcpSafe': 'HTTP MCP settings saved. Desktop-only plugin controls remain unavailable here.',
    'advanced.savedMcpDesktop': 'MCP and Desktop plugin settings saved locally.',
    'advanced.desktopOnly': 'Desktop only',
    'advanced.codeHeading': 'Sandboxed code',
    'advanced.language': 'Language',
    'advanced.timeout': 'Timeout ms',
    'advanced.saveCode': 'Save code settings',
    'advanced.codeReady': 'Code execution is Desktop-only and requires confirmation.',
    'advanced.codeUnavailableSummary': 'Sandboxed code execution is hidden on Web and Mobile.',
    'advanced.codeDesktopSummary': 'Desktop can run JavaScript/Python snippets only through the controlled sandbox runner.',
    'advanced.savedCodeUnavailable': 'Code execution settings were kept disabled because this runtime is not Desktop.',
    'advanced.savedCodeDesktop': 'Desktop sandboxed code execution settings saved locally.',
    'advanced.capabilities': 'Capabilities',
    'advanced.capabilityHeading': 'Platform matrix',
    'advanced.capabilityReady': 'Capability matrix is ready.',
    'advanced.capabilitySummary': '{platform} capability matrix: {count} available or configured surface(s).',
    'language.label': 'Language',
    'language.english': 'English',
    'language.chinese': '中文',
    'language.saved': 'Language switched to English.',
    'message.assistant': 'Assistant',
    'message.you': 'You',
    'message.edit': 'Edit',
    'message.retry': 'Retry',
    'message.now': 'now',
    'message.showEarlier': 'Show {count} earlier messages',
    'empty.caption': 'hello-world assistant',
    'empty.eyebrow': 'Local-first, multi-model, private by default',
    'empty.title': 'Start a focused workspace.',
    'empty.description': 'Use local providers, files, screenshots, voice, and model comparison from one chat surface.',
    'starter.files.label': 'Plan with files',
    'starter.files.prompt': 'Review these files and turn them into a clear action plan.',
    'starter.models.label': 'Compare models',
    'starter.models.prompt': 'Answer this with two different models and show the tradeoffs.',
    'starter.screenshot.label': 'Explain a screenshot',
    'starter.screenshot.prompt': 'Analyze this screenshot and explain what matters most.',
    'status.streaming': 'Streaming {count} chars...',
    'status.emptyResponse': '(empty response)',
    'status.unknownProviderError': 'Unknown provider error.',
    'status.providerError': 'Provider error: {message}',
    'status.typePromptCompare': 'Type a prompt before starting model comparison.',
    'status.saveProviderCompare': 'Save at least one provider before model comparison.',
    'status.comparing': 'Comparing {count} model{plural}...',
    'status.comparisonFinished': 'Comparison finished. Pick one answer to save as the main branch.',
    'status.voiceListening': 'Listening for voice input...',
    'status.noSpeech': 'No speech was captured.',
    'status.voiceAdded': 'Voice input added to the prompt.',
    'status.voiceUnknown': 'Unknown voice input error.',
    'status.voiceUnavailable': 'Voice input unavailable: {message}',
    'status.noSpeechPlayback': 'No assistant message is available for speech playback.',
    'status.speechReading': 'Reading the latest assistant reply aloud...',
    'status.speechFinished': 'Speech playback finished.',
    'status.speechUnknown': 'Unknown speech playback error.',
    'status.speechUnavailable': 'Speech playback unavailable: {message}',
    'status.savedBut': 'Saved, but {message}',
    'status.localOllamaReady': '{message} Save the provider to use it.',
    'status.desktopDetectionUnknown': 'Unknown desktop detection error.',
    'status.nativeInputUnknown': 'Unknown native input error.',
    'status.nativeInputUnavailable': 'Native image input unavailable: {message}',
    'status.imageAttached': '{name} attached. Choose a vision-capable model before asking about it.',
    'status.updatedOtherWindow': 'Updated from another window.',
    'status.desktopShortcutScreenshotName': 'Desktop shortcut screenshot',
    'status.branchSaved': 'Latest assistant reply saved as a local branch.',
    'status.branchFailed': 'Branch creation failed.',
    'status.branchPreviewing': 'Previewing branch: {title}.',
    'status.branchSelected': 'selected branch',
    'status.branchMain': 'Branch saved as the main timeline.',
    'branch.meta': '{count} message branch from {id}',
    'branch.previewing': 'Previewing',
    'branch.preview': 'Preview',
    'branch.saveMain': 'Save as main',
    'comparison.saveMain': 'Save as main branch',
    'comparison.noTokenData': 'No token data',
    'comparison.ready': 'Ready',
    'comparison.error': 'Error: {message}',
    'comparison.unknownError': 'unknown error',
    'providerDiagnostics.apiKeyRejected': 'API key rejected by {name}. Re-enter the key and confirm model-list permissions.',
    'providerDiagnostics.ollamaUnreachable': 'Ollama is not reachable. Start Ollama and check http://127.0.0.1:11434.',
    'providerDiagnostics.corsFailure': 'Network/CORS failure. For Web, use a self-hosted gateway or enable CORS on the provider endpoint.',
    'providerDiagnostics.tlsFailure': 'TLS/certificate failure. Check system time, certificate trust, or proxy certificates.',
    'providerDiagnostics.proxyFailure': 'Proxy/network route failure. Check proxy settings and provider base URL.',
    'providerDiagnostics.validationFailed': 'Provider validation failed: {message}',
    'providerDiagnostics.noModels': 'Connected, but no models were returned. Enter a model manually if the provider supports chat.',
    'providerDiagnostics.fallbackModel': 'Connected. {preferred} was not listed; fallback suggestion: {fallback}.',
    'providerDiagnostics.connectedModels': 'Connected. {models}{suffix}',
  },
  zh: {
    'app.aria': 'hello-world AI 客户端',
    'skip.composer': '跳到输入框',
    'sidebar.workspace': '工作区',
    'brand.localFirst': '本地优先',
    'action.newChat': '新对话',
    'session.conversations': '对话',
    'session.searchPlaceholder': '搜索对话',
    'session.scope': '对话范围',
    'session.scope.active': '活跃对话',
    'session.scope.archived': '归档对话',
    'session.scope.deleted': '回收站',
    'session.scope.all': '全部对话',
    'session.tag': '对话标签',
    'session.allTags': '全部标签',
    'session.history': '聊天历史',
    'session.current': '当前对话',
    'session.currentHint': '标签、置顶、归档',
    'session.tags': '标签',
    'session.tagPlaceholder': '研究, 工作',
    'session.pin': '置顶',
    'session.archive': '归档',
    'session.save': '保存对话',
    'session.moveTrash': '移到回收站',
    'session.restore': '恢复',
    'session.deleteForever': '永久删除',
    'session.status': '{active} 个活跃 / {archived} 个归档 / 共 {total} 个',
    'session.badge.pinned': '已置顶',
    'session.badge.archived': '已归档',
    'session.badge.trash': '回收站',
    'session.empty.matching': '没有匹配的对话。',
    'session.empty.archived': '没有归档对话。',
    'session.empty.default': '还没有对话。',
    'session.messageCount.one': '{count} 条消息',
    'session.messageCount.many': '{count} 条消息',
    'local.status': '本地状态',
    'local.runtimeKeysOnly': '密钥仅在运行时保存',
    'chat.aria': '聊天',
    'chat.privateWorkspace': '私密 AI 工作区',
    'chat.untitled': '未命名对话',
    'model.compatible': '原生与兼容供应商',
    'usage.tokens': '{count} 个 token',
    'settings.link': '设置',
    'branch.results': '消息分支',
    'comparison.results': '模型对比结果',
    'attachments.aria': '附件',
    'composer.tools': '输入工具',
    'composer.attach': '附件',
    'composer.screenshot': '截图',
    'composer.pasteImage': '粘贴图片',
    'composer.camera': '相机',
    'composer.voice': '语音',
    'composer.speakLast': '朗读上一条',
    'composer.placeholder': '给 hello-world 发消息...',
    'composer.message': '消息',
    'composer.send': '发送',
    'composer.branchLast': '分支上一条',
    'composer.compare': '对比',
    'composer.stop': '停止',
    'settings.aria': '设置',
    'settings.eyebrow': '工作区设置',
    'settings.title': '设置',
    'settings.description': '在聊天界面之外管理供应商、助手、提示词、路由、本地数据和安全默认值。',
    'settings.back': '返回聊天',
    'settings.sections': '分区',
    'settings.provider': '供应商',
    'settings.agent': '助手',
    'settings.prompts': '提示词',
    'settings.routing': '路由',
    'settings.cost': '成本',
    'settings.sync': '同步',
    'settings.backup': '备份',
    'settings.security': '安全',
    'settings.advanced': '高级',
    'settings.coreSetup': '核心设置',
    'settings.coreHeading': '连接、助手和提示词',
    'settings.workflow': '工作流',
    'settings.workflowHeading': '路由和成本控制',
    'settings.localData': '本地数据',
    'settings.dataHeading': '同步和备份',
    'settings.safety': '安全',
    'settings.safetyHeading': '默认阻止的能力',
    'settings.advancedHeading': 'RAG、搜索、MCP、插件和桌面代码',
    'provider.connection': '连接',
    'provider.preset': '预设',
    'provider.presetManual': '自定义 / 手动',
    'provider.presetManualReady': '可以手动填写供应商设置。',
    'provider.presetApplied': '已载入 {name} 预设，模型为 {model}。输入运行时 API 密钥后保存。',
    'provider.modelManual': '手动模型',
    'provider.category.cloud': '云端 API',
    'provider.category.gateway': '中转 / 网关',
    'provider.category.local': '本地运行时',
    'field.name': '名称',
    'field.type': '类型',
    'field.baseUrl': '基础 URL',
    'field.model': '模型',
    'field.apiKey': 'API 密钥',
    'provider.namePlaceholder': '本地 Ollama',
    'provider.modelPlaceholder': 'gpt-4.1-mini 或 llama3.2',
    'provider.keyPlaceholder': '仅运行时使用；不会持久化',
    'provider.detectOllama': '检测 Ollama',
    'action.save': '保存',
    'provider.noneConfigured': '尚未配置供应商。',
    'provider.localEcho': '尚未配置供应商。当前使用本地回显模式。',
    'provider.saved': '已保存 {name}（{model}）。API 密钥只保存在当前浏览器标签页内存中。',
    'agent.preset': '助手预设',
    'agent.persona': '角色',
    'agent.activePreset': '当前预设',
    'agent.noPreset': '无预设',
    'agent.icon': '图标',
    'agent.defaultModel': '默认模型',
    'agent.systemPrompt': '系统提示词',
    'agent.enabledTools': '启用工具',
    'agent.knowledgeBase': '知识库',
    'agent.namePlaceholder': '研究编辑',
    'agent.iconPlaceholder': 'AI',
    'agent.modelPlaceholder': '可选模型覆盖',
    'agent.promptPlaceholder': '这个助手应该如何工作？',
    'agent.toolsPlaceholder': 'file-attachments, vision-input',
    'agent.knowledge.none': '无',
    'agent.knowledge.session': '当前会话',
    'agent.knowledge.library': '资料库',
    'agent.save': '保存助手',
    'agent.noneActive': '当前没有启用预设。',
    'agent.noneActiveDetail': '当前没有启用预设。供应商调用会使用普通聊天上下文。',
    'agent.activeDetail': '{icon} {name} 已启用。系统提示词会在运行时前置；工具仍受安全默认值控制。',
    'agent.savedActive': '{icon} {name} 已用于新的供应商调用。',
    'prompt.library': '提示词库',
    'prompt.template': '模板',
    'prompt.activeTemplate': '当前模板',
    'prompt.noTemplate': '无模板',
    'prompt.title': '标题',
    'prompt.body': '模板正文',
    'prompt.variables': '变量',
    'prompt.variablesJson': '变量 JSON',
    'prompt.tags': '标签',
    'prompt.scope': '范围',
    'prompt.scope.local': '本地',
    'prompt.scope.sync': '可同步',
    'prompt.favorite': '收藏',
    'prompt.apply': '应用',
    'prompt.titlePlaceholder': '会议总结',
    'prompt.bodyPlaceholder': '为 {{ audience }} 总结 {{ topic }}。',
    'prompt.variablesPlaceholder': 'topic, audience',
    'prompt.valuesPlaceholder': '{"topic":"发布计划","audience":"团队"}',
    'prompt.tagsPlaceholder': '工作, 写作',
    'prompt.noneSelected': '未选择模板。',
    'prompt.noneSelectedDetail': '未选择模板。保存一个模板后即可复用。',
    'prompt.saved': '{title} 已保存，可随时应用。',
    'prompt.selected': '已选择 {title}。填写变量 JSON 后即可应用。',
    'prompt.chooseBeforeApply': '请先选择或保存模板再应用。',
    'prompt.applied': '{title} 已应用到输入框。',
    'prompt.appliedMissing': '已应用，但仍有未解析变量：{variables}。',
    'prompt.variablesError': '模板变量错误：{message}',
    'prompt.variablesObjectOnly': '变量 JSON 必须是对象。',
    'prompt.invalidJson': 'JSON 无效。',
    'routing.router': '模型路由',
    'routing.route': '路由',
    'routing.strategy': '策略',
    'routing.balanced': '均衡',
    'routing.cheap': '优先低价',
    'routing.fast': '优先速度',
    'routing.longContext': '长上下文',
    'routing.privacy': '优先隐私',
    'routing.fallback': '故障回退',
    'routing.noProvider': '没有可用于路由的已启用供应商。',
    'routing.chose': '已选择 {name} / {model}（{reasons}）。',
    'routing.reason.lowCostMini': '低成本小模型',
    'routing.reason.localNoBilling': '本地模型，无供应商计费',
    'routing.reason.standardRemotePricing': '标准远程定价',
    'routing.reason.smallFastModel': '速度较快的小模型',
    'routing.reason.localLatency': '本地模型延迟取决于设备',
    'routing.reason.standardLatency': '标准模型延迟',
    'routing.reason.contextWindow': '{context} 上下文窗口',
    'routing.reason.localPrivate': '本地/私有供应商',
    'routing.reason.remoteProvider': '远程供应商',
    'routing.reason.fallback': '第一个可用回退',
    'routing.reason.balanced': '均衡优先级',
    'budget.usage': '使用预算',
    'budget.dailyLimit': '每日上限',
    'budget.monthlyLimit': '每月上限',
    'budget.currency': '货币',
    'budget.save': '保存预算',
    'budget.estimated': '预计 {amount}。{message}',
    'budget.noUsage': '暂无使用',
    'budget.latestDay': '最近一天',
    'budget.latestMonth': '最近一月',
    'budget.monthlyReached': '已达到每月预算：{current} / {limit}。',
    'budget.dailyReached': '已达到每日预算：{current} / {limit}。',
    'budget.ok': '预算正常：今日 {today}，本月 {month}。',
    'sync.foundation': '同步基础',
    'sync.localSync': '本地同步',
    'sync.status': '状态',
    'sync.localOnly': '仅本地',
    'sync.enabled': '已启用',
    'sync.endpoint': '端点',
    'sync.scopes': '范围',
    'sync.preview': '预览',
    'sync.save': '保存同步',
    'sync.disabled': '本地同步已关闭。',
    'sync.counts': '同步数量',
    'sync.settingsSaved': '同步设置已保存到本地。没有发送网络请求。',
    'sync.previewOnly': '{status} 仅预览；冲突需要明确处理。',
    'sync.upload': '上传',
    'sync.download': '下载',
    'sync.conflicts': '冲突',
    'sync.noEndpoint': '尚未配置同步端点',
    'sync.noScopes': '未选择范围',
    'sync.target.chats': '对话',
    'sync.target.settings': '设置',
    'sync.target.providers': '供应商',
    'sync.target.prompts': '提示词',
    'sync.target.agents': '助手',
    'sync.target.knowledgeMetadata': '知识元数据',
    'sync.conflictNeedsReview': '{count} 个冲突需要明确处理后才能同步。',
    'sync.noPendingAt': '截至 {checkedAt} 没有待同步变更。',
    'sync.noPending': '没有待同步变更。',
    'sync.readyCounts': '{upload} 个上传和 {download} 个下载已准备好。',
    'backup.importExport': '导入 / 导出',
    'backup.description': '导出单个会话 Markdown，或导出用于完整本地恢复的 JSON。',
    'backup.payload': '备份内容',
    'backup.payloadPlaceholder': '导出的 Markdown 或 hello-world JSON 备份会显示在这里。恢复前也可以把 JSON 粘贴到这里。',
    'backup.markdown': 'Markdown',
    'backup.json': 'JSON 备份',
    'backup.restore': '恢复',
    'backup.ready': '已准备好导出本地数据。',
    'backup.readyDetail': '已准备好导出：{summary}',
    'backup.jsonReady': 'JSON 备份已生成：{summary} 请保存到本地文件。',
    'backup.markdownReady': '当前会话 Markdown 已生成，并已脱敏明显敏感内容。',
    'backup.restored': '备份已在本地恢复。供应商 API 密钥需要在运行时重新输入。',
    'backup.restoreFailed': '恢复失败：{message}',
    'backup.invalidJson': '备份 JSON 无效。',
    'backup.summary': '{sessions} 个对话，{prompts} 个提示词，{agents} 个助手，{providers} 个供应商。',
    'security.defaults': '安全默认值',
    'security.terminal': '终端',
    'security.codeExecution': '代码执行',
    'security.stdioMcp': 'stdio MCP',
    'security.broadFilesystem': '宽泛文件系统',
    'security.off': '关闭',
    'advanced.enabled': '启用',
    'advanced.rag': 'RAG',
    'advanced.ragHeading': '知识检索',
    'advanced.sourceScope': '来源范围',
    'advanced.scopeSession': '会话',
    'advanced.scopeLibrary': '资料库',
    'advanced.scopeBoth': '会话 + 资料库',
    'advanced.embeddingProvider': '向量供应',
    'advanced.localEmbedding': '本地确定性',
    'advanced.remoteEmbedding': '远程运行时供应商',
    'advanced.indexMode': '索引模式',
    'advanced.lightweightIndex': 'Web/Mobile 轻量',
    'advanced.desktopDurableIndex': 'Desktop 持久',
    'advanced.retrievalMode': '检索',
    'advanced.maxChunks': '最大 chunks',
    'advanced.requireCitations': '必须引用',
    'advanced.reranking': '重排',
    'advanced.saveRag': '保存 RAG',
    'advanced.ragReady': 'RAG 设置已准备好。',
    'advanced.ragSummary': '{scope} 检索使用 {retrieval} 模式，最多 {chunks} 个 chunk。',
    'advanced.savedRag': 'RAG 设置已在本地保存。',
    'advanced.webSearch': 'Web search',
    'advanced.webSearchHeading': '带引用的答案',
    'advanced.searchProvider': '供应商',
    'advanced.custom': '自定义',
    'advanced.maxResults': '最大结果',
    'advanced.groundedAnswers': '带引用答案',
    'advanced.desktopProxy': 'Desktop 代理回退',
    'advanced.saveWebSearch': '保存搜索',
    'advanced.webSearchReady': '搜索设置已准备好。',
    'advanced.webSearchSummary': '{provider} 已配置，最多 {results} 个结果。',
    'advanced.savedWebSearch': 'Web search 设置已在本地保存。运行时搜索密钥不会持久化。',
    'advanced.mcp': 'MCP / 插件',
    'advanced.mcpHeading': '工具服务',
    'advanced.httpMcp': 'HTTP MCP',
    'advanced.tools': '工具',
    'advanced.pluginManager': 'Desktop 插件管理',
    'advanced.stdioMcp': 'Desktop stdio MCP',
    'advanced.requireConfirmation': '需要确认',
    'advanced.saveMcp': '保存 MCP',
    'advanced.mcpReady': 'MCP 设置已准备好。',
    'advanced.mcpSharedSummary': 'HTTP MCP 是三端共享的安全子集。Desktop-only 控件在这里不可用。',
    'advanced.mcpDesktopSummary': 'Desktop 插件控件已显示，但仍需要确认和策略门禁。',
    'advanced.savedMcpSafe': 'HTTP MCP 设置已保存。Desktop-only 插件控件在此运行时不可用。',
    'advanced.savedMcpDesktop': 'MCP 和 Desktop 插件设置已在本地保存。',
    'advanced.desktopOnly': '仅 Desktop',
    'advanced.codeHeading': '沙箱代码',
    'advanced.language': '语言',
    'advanced.timeout': '超时 ms',
    'advanced.saveCode': '保存代码设置',
    'advanced.codeReady': '代码执行仅限 Desktop，并需要确认。',
    'advanced.codeUnavailableSummary': '沙箱代码执行在 Web 和 Mobile 隐藏。',
    'advanced.codeDesktopSummary': 'Desktop 只能通过受控沙箱运行 JavaScript/Python 片段。',
    'advanced.savedCodeUnavailable': '当前运行时不是 Desktop，代码执行设置保持关闭。',
    'advanced.savedCodeDesktop': 'Desktop 沙箱代码执行设置已在本地保存。',
    'advanced.capabilities': '能力',
    'advanced.capabilityHeading': '平台矩阵',
    'advanced.capabilityReady': '能力矩阵已准备好。',
    'advanced.capabilitySummary': '{platform} 能力矩阵：{count} 个可用或已配置的表面。',
    'language.label': '语言',
    'language.english': 'English',
    'language.chinese': '中文',
    'language.saved': '语言已切换为中文。',
    'message.assistant': '助手',
    'message.you': '你',
    'message.edit': '编辑',
    'message.retry': '重试',
    'message.now': '刚刚',
    'message.showEarlier': '显示前面 {count} 条消息',
    'empty.caption': 'hello-world 助手',
    'empty.eyebrow': '本地优先、多模型、默认私密',
    'empty.title': '开始一个专注工作区。',
    'empty.description': '在同一个聊天界面使用本地供应商、文件、截图、语音和模型对比。',
    'starter.files.label': '用文件规划',
    'starter.files.prompt': '阅读这些文件，并整理成清晰的行动计划。',
    'starter.models.label': '对比模型',
    'starter.models.prompt': '用两个不同模型回答这个问题，并展示取舍。',
    'starter.screenshot.label': '解释截图',
    'starter.screenshot.prompt': '分析这张截图，并说明最重要的信息。',
    'status.streaming': '正在流式输出 {count} 个字符...',
    'status.emptyResponse': '（空响应）',
    'status.unknownProviderError': '未知供应商错误。',
    'status.providerError': '供应商错误：{message}',
    'status.typePromptCompare': '请先输入提示词再开始模型对比。',
    'status.saveProviderCompare': '请先保存至少一个供应商再进行模型对比。',
    'status.comparing': '正在对比 {count} 个模型...',
    'status.comparisonFinished': '对比完成。选择一个答案保存为主分支。',
    'status.voiceListening': '正在监听语音输入...',
    'status.noSpeech': '没有捕获到语音。',
    'status.voiceAdded': '语音输入已添加到输入框。',
    'status.voiceUnknown': '未知语音输入错误。',
    'status.voiceUnavailable': '语音输入不可用：{message}',
    'status.noSpeechPlayback': '没有可朗读的助手消息。',
    'status.speechReading': '正在朗读最新助手回复...',
    'status.speechFinished': '朗读完成。',
    'status.speechUnknown': '未知语音播放错误。',
    'status.speechUnavailable': '语音播放不可用：{message}',
    'status.savedBut': '已保存，但 {message}',
    'status.localOllamaReady': '{message} 保存该供应商后即可使用。',
    'status.desktopDetectionUnknown': '未知桌面检测错误。',
    'status.nativeInputUnknown': '未知原生输入错误。',
    'status.nativeInputUnavailable': '原生图片输入不可用：{message}',
    'status.imageAttached': '{name} 已附加。请先选择支持视觉的模型再提问。',
    'status.updatedOtherWindow': '已从另一个窗口更新。',
    'status.desktopShortcutScreenshotName': '桌面快捷键截图',
    'status.branchSaved': '最新助手回复已保存为本地分支。',
    'status.branchFailed': '分支创建失败。',
    'status.branchPreviewing': '正在预览分支：{title}。',
    'status.branchSelected': '所选分支',
    'status.branchMain': '分支已保存为主时间线。',
    'branch.meta': '来自 {id} 的 {count} 条消息分支',
    'branch.previewing': '正在预览',
    'branch.preview': '预览',
    'branch.saveMain': '保存为主线',
    'comparison.saveMain': '保存为主分支',
    'comparison.noTokenData': '无 token 数据',
    'comparison.ready': '已就绪',
    'comparison.error': '错误：{message}',
    'comparison.unknownError': '未知错误',
    'providerDiagnostics.apiKeyRejected': '{name} 拒绝了 API 密钥。请重新输入密钥并确认模型列表权限。',
    'providerDiagnostics.ollamaUnreachable': '无法连接 Ollama。请启动 Ollama 并检查 http://127.0.0.1:11434。',
    'providerDiagnostics.corsFailure': '网络/CORS 失败。Web 端请使用自托管网关，或在供应商端点启用 CORS。',
    'providerDiagnostics.tlsFailure': 'TLS/证书失败。请检查系统时间、证书信任或代理证书。',
    'providerDiagnostics.proxyFailure': '代理/网络路由失败。请检查代理设置和供应商 Base URL。',
    'providerDiagnostics.validationFailed': '供应商验证失败：{message}',
    'providerDiagnostics.noModels': '已连接，但未返回模型。如果供应商支持聊天，请手动输入模型。',
    'providerDiagnostics.fallbackModel': '已连接。未列出 {preferred}；建议回退到 {fallback}。',
    'providerDiagnostics.connectedModels': '已连接。{models}{suffix}',
  },
};

export function normalizeLocale(value) {
  return supportedLocales.includes(value) ? value : 'en';
}

export function createTranslator(locale) {
  const normalized = normalizeLocale(locale);
  return (key, values = {}) => {
    const template = dictionaries[normalized][key] ?? dictionaries.en[key] ?? key;
    return Object.entries(values).reduce(
      (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
      template,
    );
  };
}

export function applyTranslations(root, locale) {
  const normalized = normalizeLocale(locale);
  const t = createTranslator(normalized);
  const documentElement = root.documentElement ?? root.ownerDocument?.documentElement;
  if (documentElement) {
    documentElement.lang = normalized === 'zh' ? 'zh-CN' : 'en';
  }
  for (const element of queryAll(root, '[data-i18n]')) {
    element.textContent = t(element.dataset.i18n);
  }
  for (const element of queryAll(root, '[data-i18n-placeholder]')) {
    element.setAttribute('placeholder', t(element.dataset.i18nPlaceholder));
  }
  for (const element of queryAll(root, '[data-i18n-aria-label]')) {
    element.setAttribute('aria-label', t(element.dataset.i18nAriaLabel));
  }
  for (const element of queryAll(root, '[data-i18n-label]')) {
    setLeadingLabelText(element, t(element.dataset.i18nLabel));
  }
  return t;
}

function queryAll(root, selector) {
  return Array.from(root.querySelectorAll?.(selector) ?? []);
}

function setLeadingLabelText(element, text) {
  const prefix = `${text} `;
  const firstChild = element.childNodes?.[0];
  if (firstChild?.nodeType === 3) {
    firstChild.nodeValue = prefix;
    return;
  }
  const ownerDocument = element.ownerDocument ?? document;
  element.insertBefore(ownerDocument.createTextNode(prefix), firstChild ?? null);
}
